<a href="https://colab.research.google.com/github/Prathyusha-Pasupuleti/Numpy/blob/main/Introduction_to_Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [2]:
# Recap
arr = np.array([[1,2,3],[4,5,6]])

In [4]:
type(arr)

numpy.ndarray

In [20]:

# Dot product - m x n || n x p
arr1 = np.random.randint(1,2,(1,2))

In [21]:
arr.shape
arr1.shape

(1, 2)

In [9]:
result = np.dot(arr,arr1)

In [10]:
print(result)

[[ 6]
 [15]]


In [12]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[15 16 14]
 [15 14 13]
 [11 15 11]]


In [13]:
r2 = np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# r1 . I
result2 = np.dot(r2,r1)

In [17]:
print(result2)

[[15. 16. 14.]
 [15. 14. 13.]
 [11. 15. 11.]]


In [ ]:
# M . I = I . M = M

# A . B != B . A

In [23]:
# MATHEMATICAL OPERATIONS
# + - * /
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))

In [24]:
print(t1)
print(t2)

[[4 4 3]
 [4 3 4]
 [3 4 5]]
[[5 4 5]
 [3 4 3]
 [5 4 3]]


In [26]:
t3 = t1 +t2
print(t3)

[[9 8 8]
 [7 7 7]
 [8 8 8]]


In [27]:
# Matrix multiplication
result = np.dot(arr1,arr)

In [37]:
# Statistical multiplication
mean = t3.mean()
max = t3.max()
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)

In [38]:
print(mean)
print(max)
print(median)
print(std)
print(var)

7.777777777777778
9
8.0
0.6285393610547089
0.3950617283950617


In [39]:
std * std

0.39506172839506165

In [49]:
# Trigonometric functions
# Sin - (x)
# Cos - (x)
# Tan - sin(x)/cos(x)
# Cosec - 1/ sin(x)
# Sec - 1 / cos(x)
# Cot - 1 / tan(x)
#
angles = np.array([0,15,30,45,60,75,90])

# Sin (array)

result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))

In [47]:
print(result)
print(result1)
print(result2)

[0.17364818 0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[9.84807753e-01 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[1.76326981e-01 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [48]:
arr = np.array([1,2,3,4,5,6])

# Reshape the array
reshapedarr = arr.reshape(3,2)

print(reshapedarr)

# Convert / Flatten any n dim array
flattenedarr = arr.flatten()

print(flattenedarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [52]:
# Stacking the data

arr1 = np.array([[1,2,3,4],[2,3,4,5]])
arr2 = np.array([10,20,30,40])

# Vertical Stacking
arr3 = np.vstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")

The shape of arr3 is (3, 4)


In [53]:
# Stacking the data

arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

# Vertical Stacking
arr3 = np.vstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")

# Horizontal Stacking
arr4 = np.hstack((arr1,arr2))
print(f"The shape of arr4 is {arr4.shape}")
print(arr4)

The shape of arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [54]:
# Filtering
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr[arr > 40]

print(farr)

[50 60 70 80]
